#!/usr/bin/env python3
"""
Foreclosure Finder — Daily Pipeline Orchestrator
=================================================
Reads the source list from config.py and runs every enabled source in sequence.
This is the single entry point for the daily launchd job.

Usage:
    python3 scripts/run.py                  # full run (scrape + sync + push)
    python3 scripts/run.py --no-sync        # scrape only, skip Google Sheets
    python3 scripts/run.py --no-push        # skip GitHub Pages publish

To enable or disable a source, edit COLUMN_US_SOURCES in scripts/config.py.
Do NOT edit this file to control which sources run.
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..")

sys.path.insert(0, SCRIPT_DIR)
import config as cfg


def run(cmd: list[str], label: str) -> bool:
    """Run a subprocess command, stream output, return True on success."""
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print(f"  [error] {label} exited with code {result.returncode}")
        return False
    return True


def main():
    parser = argparse.ArgumentParser(description="Foreclosure pipeline orchestrator")
    parser.add_argument("--no-sync", action="store_true", help="Skip Google Sheets sync")
    parser.add_argument("--no-push", action="store_true", help="Skip GitHub Pages publish")
    args = parser.parse_args()

    sync = not args.no_sync
    push = not args.no_push

    python = sys.executable

    print()
    print("=" * 60)
    print("  Virginia Foreclosure Pipeline")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Sync to Google Sheets: {sync}")
    print(f"  Push to GitHub Pages:  {push}")
    print("=" * 60)

    # ── Enabled sources ───────────────────────────────────────────
    active = [s for s in cfg.COLUMN_US_SOURCES if s["enabled"]]
    skipped = [s for s in cfg.COLUMN_US_SOURCES if not s["enabled"]]
    print(f"\nSources enabled:  {len(active)}")
    print(f"Sources disabled: {len(skipped)}")

    # ── Run each enabled source ───────────────────────────────────
    for source in active:
        print()
        print("-" * 60)
        print(f"  {source['label']}")
        print("-" * 60)

        output_path = os.path.join(PROJECT_ROOT, source["output"])

        ok = run(
            [
                python, "scripts/scraper_column_us.py",
                "--url",    source["url"],
                "--header", source["header"],
                "--source", source["source_tag"],
                "--output", output_path,
                "--label",  source["label"],
            ],
            source["label"]
        )

        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", output_path],
                f"sheets sync — {source['label']}"
            )

    # ── Skipped sources summary ───────────────────────────────────
    if skipped:
        print()
        print("--- Disabled sources (not run) ---")
        for s in skipped:
            print(f"  {s['label']:45s}  {s['notes']}")

    # ── SIWPC PDF scraper ─────────────────────────────────────────
    if cfg.ENABLE_SIWPC:
        print()
        print("-" * 60)
        print("  Samuel I. White, P.C. (SIWPC PDF)")
        print("-" * 60)
        siwpc_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_siwpc.json")
        ok = run(
            [python, "scripts/scraper_siwpc.py", "--output", siwpc_output],
            "SIWPC scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", siwpc_output],
                "sheets sync — SIWPC"
            )
    else:
        print()
        print("  SIWPC: SKIPPED (ENABLE_SIWPC=False in config.py)")

    # ── Auction Network ───────────────────────────────────────────
    if cfg.ENABLE_AUCTIONNETWORK:
        print()
        print("-" * 60)
        print("  Auction Network (bid.auctionnetwork.com)")
        print("-" * 60)
        an_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_auctionnetwork.json")
        ok = run(
            [python, "scripts/scraper_auctionnetwork.py"],
            "Auction Network scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", an_output],
                "sheets sync — Auction Network"
            )
    else:
        print()
        print("  Auction Network: SKIPPED (ENABLE_AUCTIONNETWORK=False in config.py)")

    # ── Glasser Law ───────────────────────────────────────────────
    if cfg.ENABLE_GLASSERLAW:
        print()
        print("-" * 60)
        print("  Glasser Law (glasserlaw.com)")
        print("-" * 60)
        gl_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_glasserlaw.json")
        ok = run(
            [python, "scripts/scraper_glasserlaw.py"],
            "Glasser Law scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", gl_output],
                "sheets sync — Glasser Law"
            )
    else:
        print()
        print("  Glasser Law: SKIPPED (ENABLE_GLASSERLAW=False in config.py)")

    # ── MWC Law ───────────────────────────────────────────────────
    if cfg.ENABLE_MWCLAW:
        print()
        print("-" * 60)
        print("  MWC Law (apps.mwc-law.com)")
        print("-" * 60)
        mwc_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_mwclaw.json")
        ok = run(
            [python, "scripts/scraper_mwclaw.py"],
            "MWC Law scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", mwc_output],
                "sheets sync — MWC Law"
            )
    else:
        print()
        print("  MWC Law: SKIPPED (ENABLE_MWCLAW=False in config.py)")

    # ── LOGS Legal Group LLP ─────────────────────────────────────
    if cfg.ENABLE_LOGS:
        print()
        print("-" * 60)
        print("  LOGS Legal Group LLP (logs.com/va-sales-report.html)")
        print("-" * 60)
        logs_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_logs.json")
        ok = run(
            [python, "scripts/scraper_logs.py"],
            "LOGS Legal scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", logs_output],
                "sheets sync — LOGS Legal"
            )
    else:
        print()
        print("  LOGS Legal: SKIPPED (ENABLE_LOGS=False in config.py)")

    # ── Auction.com ───────────────────────────────────────────────
    if cfg.ENABLE_AUCTIONCOM:
        print()
        print("-" * 60)
        print("  Auction.com (GOTO foreclosures — live courthouse sales)")
        print("-" * 60)
        ac_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_auctioncom.json")
        ok = run(
            [python, "scripts/scraper_auctioncom.py"],
            "Auction.com scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", ac_output],
                "sheets sync — Auction.com"
            )
    else:
        print()
        print("  Auction.com: SKIPPED (ENABLE_AUCTIONCOM=False in config.py)")

    # ── Xome Auctions ─────────────────────────────────────────────
    if cfg.ENABLE_XOME:
        print()
        print("-" * 60)
        print("  Xome Auctions (xome.com/auctions/foreclosuresales)")
        print("-" * 60)
        xome_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_xome.json")
        ok = run(
            [python, "scripts/scraper_xome.py"],
            "Xome Auction scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", xome_output],
                "sheets sync — Xome"
            )
    else:
        print()
        print("  Xome: SKIPPED (ENABLE_XOME=False in config.py)")

    # ── ServiceLink Auction ───────────────────────────────────────
    if cfg.ENABLE_SERVICELINK:
        print()
        print("-" * 60)
        print("  ServiceLink Auction (servicelinkauction.com)")
        print("-" * 60)
        sl_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_servicelink.json")
        ok = run(
            [python, "scripts/scraper_servicelink.py"],
            "ServiceLink Auction scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", sl_output],
                "sheets sync — ServiceLink"
            )
    else:
        print()
        print("  ServiceLink Auction: SKIPPED (ENABLE_SERVICELINK=False in config.py)")

    # ── Rosenberg & Associates ────────────────────────────────────
    if cfg.ENABLE_ROSENBERG:
        print()
        print("-" * 60)
        print("  Rosenberg & Associates (rosenberg-assoc.com)")
        print("-" * 60)
        ra_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_rosenberg.json")
        ok = run(
            [python, "scripts/scraper_rosenberg.py"],
            "Rosenberg & Associates scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", ra_output],
                "sheets sync — Rosenberg & Associates"
            )
    else:
        print()
        print("  Rosenberg & Associates: SKIPPED (ENABLE_ROSENBERG=False in config.py)")

    # ── Brock & Scott PLLC ───────────────────────────────────────
    if cfg.ENABLE_BROCKSCOTT:
        print()
        print("-" * 60)
        print("  Brock & Scott, PLLC (brockandscott.com)")
        print("-" * 60)
        bs_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_brockscott.json")
        ok = run(
            [python, "scripts/scraper_brockscott.py"],
            "Brock & Scott scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", bs_output],
                "sheets sync — Brock & Scott"
            )
    else:
        print()
        print("  Brock & Scott: SKIPPED (ENABLE_BROCKSCOTT=False in config.py)")

    # ── Washington Times Classifieds ─────────────────────────────
    if cfg.ENABLE_WASHINGTONTIMES:
        print()
        print("-" * 60)
        print("  The Washington Times (classified.washingtontimes.com)")
        print("-" * 60)
        wt_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_washingtontimes.json")
        ok = run(
            [python, "scripts/scraper_washingtontimes.py", "--output", wt_output],
            "Washington Times scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", wt_output],
                "sheets sync — Washington Times"
            )
    else:
        print()
        print("  Washington Times: SKIPPED (ENABLE_WASHINGTONTIMES=False in config.py)")

    # ── PNV — PublicNoticeVirginia.com ────────────────────────────
    if cfg.ENABLE_PNV:
        print()
        print("-" * 60)
        print("  PublicNoticeVirginia.com (PNV — card text mode)")
        print("-" * 60)
        pnv_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_pnv.json")
        ok = run(
            [python, "scripts/scraper.py", "--pnv-run", "--output", pnv_output],
            "PNV scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", pnv_output],
                "sheets sync — PNV"
            )
    else:
        print()
        print("  PNV: SKIPPED (ENABLE_PNV=False in config.py)")

    # ── GitHub Pages publish ──────────────────────────────────────
    if push and active:
        print()
        print("-" * 60)
        print("  Publishing to GitHub Pages...")
        print("-" * 60)
        build_script = os.path.join(PROJECT_ROOT, "scripts", "build_site.py")
        if os.path.exists(build_script):
            run([python, "scripts/build_site.py"], "build site")

        import subprocess as sp
        result = sp.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=PROJECT_ROOT
        )
        sp.run(["git", "add", "-A"], cwd=PROJECT_ROOT)
        result = sp.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=PROJECT_ROOT
        )
        if result.returncode != 0:
            sp.run(
                ["git", "commit", "-m",
                 f"Auto-update: {datetime.now().strftime('%Y-%m-%d %H:%M')}"],
                cwd=PROJECT_ROOT
            )
            sp.run(["git", "push", "origin", "main"], cwd=PROJECT_ROOT)
            print("  Pushed to GitHub Pages.")
        else:
            print("  No changes to commit.")

    print()
    print("=" * 60)
    print(f"  Pipeline complete — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
