#!/usr/bin/env python3
"""
Foreclosure Finder — Daily Pipeline Orchestrator
=================================================
Reads the source list from config.py and runs every enabled source in sequence.
This is the single entry point for the daily launchd job.

Usage:
    python3 scripts/run.py                  # full run (scrape + sync + push)
    python3 scripts/run.py --no-sync        # scrape only, skip Google Sheets
    python3 scripts/run.py --no-push        # skip GitHub Pages publish

To enable or disable a source, edit COLUMN_US_SOURCES in scripts/config.py.
Do NOT edit this file to control which sources run.
"""

import argparse
import os
import subprocess
import sys
from datetime import datetime

SCRIPT_DIR   = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.join(SCRIPT_DIR, "..")

sys.path.insert(0, SCRIPT_DIR)
import config as cfg


def run(cmd: list[str], label: str) -> bool:
    """Run a subprocess command, stream output, return True on success."""
    result = subprocess.run(cmd, cwd=PROJECT_ROOT)
    if result.returncode != 0:
        print(f"  [error] {label} exited with code {result.returncode}")
        return False
    return True


def main():
    parser = argparse.ArgumentParser(description="Foreclosure pipeline orchestrator")
    parser.add_argument("--no-sync", action="store_true", help="Skip Google Sheets sync")
    parser.add_argument("--no-push", action="store_true", help="Skip GitHub Pages publish")
    args = parser.parse_args()

    sync = not args.no_sync
    push = not args.no_push

    python = sys.executable

    print()
    print("=" * 60)
    print("  Virginia Foreclosure Pipeline")
    print(f"  {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print(f"  Sync to Google Sheets: {sync}")
    print(f"  Push to GitHub Pages:  {push}")
    print("=" * 60)

    # ── Enabled sources ───────────────────────────────────────────
    active = [s for s in cfg.COLUMN_US_SOURCES if s["enabled"]]
    skipped = [s for s in cfg.COLUMN_US_SOURCES if not s["enabled"]]
    print(f"\nSources enabled:  {len(active)}")
    print(f"Sources disabled: {len(skipped)}")

    # ── Clear sheet before first source runs ──────────────────────
    if sync and active:
        print("\n--- Clearing Google Sheet (fresh start) ---")
        ok = run(
            [python, "scripts/sheets_sync.py", "--clear-only"],
            "sheet clear"
        )
        if not ok:
            print("\n  ✗ Sheet clear failed — aborting.")
            print("  Continuing with a stale sheet would corrupt column order.")
            sys.exit(1)

    # ── Run each enabled source ───────────────────────────────────
    for source in active:
        print()
        print("-" * 60)
        print(f"  {source['label']}")
        print("-" * 60)

        output_path = os.path.join(PROJECT_ROOT, source["output"])

        ok = run(
            [
                python, "scripts/scraper_column_us.py",
                "--url",    source["url"],
                "--header", source["header"],
                "--source", source["source_tag"],
                "--output", output_path,
                "--label",  source["label"],
            ],
            source["label"]
        )

        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", output_path],
                f"sheets sync — {source['label']}"
            )

    # ── Skipped sources summary ───────────────────────────────────
    if skipped:
        print()
        print("--- Disabled sources (not run) ---")
        for s in skipped:
            print(f"  {s['label']:45s}  {s['notes']}")

    # ── SIWPC PDF scraper ─────────────────────────────────────────
    if cfg.ENABLE_SIWPC:
        print()
        print("-" * 60)
        print("  Samuel I. White, P.C. (SIWPC PDF)")
        print("-" * 60)
        siwpc_output = os.path.join(PROJECT_ROOT, "data", "foreclosures_siwpc.json")
        ok = run(
            [python, "scripts/scraper_siwpc.py", "--output", siwpc_output],
            "SIWPC scraper"
        )
        if ok and sync:
            run(
                [python, "scripts/sheets_sync.py", "--file", siwpc_output],
                "sheets sync — SIWPC"
            )
    else:
        print()
        print("  SIWPC: SKIPPED (ENABLE_SIWPC=False in config.py)")

    # ── GitHub Pages publish ──────────────────────────────────────
    if push and active:
        print()
        print("-" * 60)
        print("  Publishing to GitHub Pages...")
        print("-" * 60)
        build_script = os.path.join(PROJECT_ROOT, "scripts", "build_site.py")
        if os.path.exists(build_script):
            run([python, "scripts/build_site.py"], "build site")

        import subprocess as sp
        result = sp.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=PROJECT_ROOT
        )
        sp.run(["git", "add", "-A"], cwd=PROJECT_ROOT)
        result = sp.run(
            ["git", "diff", "--cached", "--quiet"],
            cwd=PROJECT_ROOT
        )
        if result.returncode != 0:
            sp.run(
                ["git", "commit", "-m",
                 f"Auto-update: {datetime.now().strftime('%Y-%m-%d %H:%M')}"],
                cwd=PROJECT_ROOT
            )
            sp.run(["git", "push", "origin", "main"], cwd=PROJECT_ROOT)
            print("  Pushed to GitHub Pages.")
        else:
            print("  No changes to commit.")

    print()
    print("=" * 60)
    print(f"  Pipeline complete — {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}")
    print("=" * 60)
    print()


if __name__ == "__main__":
    main()
